### ISSUE TITLE
`url` field not prefilled when using Provisioning config file

### ISSUE THREAD

**Issue by mountainash** [golioth/grafana-websocket-plugin#22]
When going in to edit the Data Sources on Grafana the host/endpoint is correctly shown in the "Overview" of data sources.

![The Grafana Data Sources overview screen](https://user-images.githubusercontent.com/27637/190091852-6ba4375d-fca8-444a-b616-a1787af0d8fa.png)

But when you click through to edit/see all the settings for the WebSocket API data source the "Host"  input field is empty.

![WebSocket API data source settings screen](https://user-images.githubusercontent.com/27637/190091163-9a021ef6-2005-450e-9718-484967f69075.png)

To be consistent with other Data Sources this should contain the same value set by the [Provisioning config file](https://grafana.com/docs/grafana/latest/administration/provisioning/) `url` value.

```yaml
  - name: WebSocket API
    type: golioth-websocket-datasource
    orgId: 1
    access: proxy
    uid: grafana_wsapi
    url: ${WSAPI_URL}
    isDefault: true
    version: 1
    editable: true
```

Tested with Grafana v8.3.4 & WebSocket API v1.0.1

**Comment by mountainash** [comment]
I dug and found a that the format for setting a default host for this plugin is `jsonDate`>`host`, eg:
```yaml
  - name: WebSocket API
    type: golioth-websocket-datasource
    uid: grafana_wsapi
    orgId: 1
    access: proxy
    jsonData:
      host: ${WSAPI_URL}
    isDefault: true
    version: 1
    editable: true
```

But to be inline with other plugins (like Postgres and Redis) it would be more intuitive to use `url` as parent key name.
